<a href="https://colab.research.google.com/github/abhishekmarkad/Campusx/blob/main/session_14_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Find the nearest element in the array to a given integer.
```
Ex:-
a=23 and array - [10 17 24 31 38 45 52 59].
Nearest element is 24
```
Hint: Read about this function `argmin()`

In [ ]:
import numpy as np

###`Q-2:` Replace multiples of 3 or 5 as 0 in the given array.
```
arr=[1 2 3 4 5 6 7 9]

result-> [1 2 0 4 0 0 7 0]
```

In [ ]:
# code here
arr=np.array([1,2,3,4,5,6,7,9])

arr[(arr%3==0) | (arr%5==0)]=0
arr

array([1, 2, 0, 4, 0, 0, 7, 0])

###`Q-3:` Use Fancy Indexing.
1. Double the array elements at  given indexes
```
arr = np.arrange(10)
indexes = [0,3,4,9]
```
Result -> `[ 0  1  2  6  8  5  6  7  8 18]`

2. Using a given array make a different array as in below example
```
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
```
* Internal-repetion should be as length of the array.

Hint:
```
if a is an array
a = [2,4]
a[[1,1,0,1]] will result in-> [4 4 2 4]
```

In [ ]:
# code here
arr=np.arange(10)
indexes = [0,3,4,9]
arr[indexes]=arr[indexes]*3

arr

array([ 0,  1,  2,  6,  8,  5,  6,  7,  8, 18])

In [ ]:
array = np.array([1,2,3])

array[[ind for ind in range(len(array)) for _ in range(len(array))]]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

###`Q-4:` Your are given an array which is havig some nan value. You job is to fill those nan values with most common element in the array.
```
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

```

In [ ]:
# code here

import statistics as st
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

val,count=np.unique(arr,return_counts=True)
mode=val[0]
mode_count=count[0]
for i in range(len(val)):
  if(mode_count<count[i]):
    mode=val[i]
    mode_count=count[i]

arr[arr==np.nan]=mode
arr

array([[ 1.,  2., nan],
       [ 4.,  2.,  6.],
       [nan, nan,  5.]])

### `Q-5:` Write a NumPy program

- to find the missing data in a given array. Return a boolean matrix.
- also try to fill those missing values with 0. For that, you can use `np.nan_to_num(a)`

```python
import numpy as np

np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
```

In [ ]:
# code here
np.nan_to_num(arr)

array([[1., 2., 0.],
       [4., 2., 6.],
       [0., 0., 5.]])

###`Q-6:` Given two arrays, X and Y, construct the Cauchy matrix C.
`Cij =1/(xi - yj)`

http://en.wikipedia.org/wiki/Cauchy_matrix
```
x = numpy.array([1,2,3,4]).reshape((-1, 1)
y = numpy.array([5,6,7])
```

In [ ]:
# code here\
x = np.array([1,2,3,4]).reshape((-1, 1))
y = np.array([5,6,7])

In [ ]:
1/(x-y)

array([[-0.25      , -0.2       , -0.16666667],
       [-0.33333333, -0.25      , -0.2       ],
       [-0.5       , -0.33333333, -0.25      ],
       [-1.        , -0.5       , -0.33333333]])

###`Q-7:` Plot this below equation.

$$\large y = \frac{e^x - e^{-x}}{e^x + e^{-x}}$$

**Note: This equation is called tanh activation function. In deep learning, many times this function is used. If you find some difference between the sigmoid function and this tanh function, note that to your notebook.**

In [ ]:
# code here
x=np.linspace(-5,5,100)

In [ ]:
y=(np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))

In [ ]:
import matplotlib.pyplot as plt
plt.plot(x,y)

### `Q-8:` Plot the below equation.

$$\large y = \sqrt{36 - (x - 4)^2} + 2$$

The range of x should be between -2 to 10. $x ∈ [-2, 10]$



In [ ]:
x=np.linspace(-2,10,100)

In [ ]:
y=np.sqrt(36-(x-4)**2+2)

In [ ]:
plt.plot(x,y)

### `Q-9:` Write a program implement Boradcasting Rule to check if two array can be added or not.
Given tuples of shapes.
```
shape of a- (3,2,2)
shape of b- (2,2)

check_broadcast(a, b) -> return Boolean (True if can broadcasted, False other wise.)
```

In [ ]:
# code here
def make_equal_length(a,b):
  if(len(a)==len(b)):
    return (a,b)
  if(len(a)<len(b)):
    tmp=[1]*(len(b)-len(a))
    tmp.extend(a)
    return (tmp,list(b))
  tmp=([1]*(len(a)-len(b)))
  tmp.extend(b)
  return (list(a),tmp)
def check_broadcast(a,b):
  a,b=make_equal_length(a,b)
  for i in range(len(a)):
    if(a[i]!=b[i] and (a[i]!=1 and b[i]!=1)):
      return False
  return True

check_broadcast((3,2,2),(4,2,2))


False

In [ ]:
([1]*3)
# .extend([2,3])

[1, 1, 1]

In [ ]:
a=[1,1,1]
a.extend([2,3])
a

[1, 1, 1, 2, 3]