<a href="https://colab.research.google.com/github/abhishekmarkad/Campusx/blob/main/Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
vector=np.empty(10)*np.nan
vector[4]=1
vector

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a=int(input('enter first varible'))
b=int(input('enter second varible'))
array=np.random.random((a,b))
print(array)

np.mean(a)

enter first varible3
enter second varible3
[[0.43146323 0.13236058 0.76620172]
 [0.70962349 0.8020498  0.66264817]
 [0.30675389 0.92010752 0.7197712 ]]


3.0

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
def create_2d(a:int,b:int):
  array=np.zeros((a,b),dtype=int)
  array[[0,b-1]]=1
  array[:,[0,b-1]]=1
  return array

create_2d(4,4)

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
np.random.random_integers(0,4,size=25).reshape(5,5)

<ipython-input-17-0f518dc40ad2>:2: DeprecationWarning: This function is deprecated. Please call randint(0, 4 + 1) instead
  np.random.random_integers(0,4,size=25).reshape(5,5)


array([[1, 1, 0, 0, 2],
       [2, 4, 1, 0, 1],
       [0, 0, 4, 4, 2],
       [2, 1, 0, 0, 0],
       [2, 2, 1, 1, 2]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
coordinates=np.random.random_integers(1,100,size=20).reshape(10,2)
coordinates
point=np.array([2,3])
print(coordinates)
distance=coordinates

print(((coordinates-point)**2))
distance=(np.sum(((coordinates-point)**2),axis=1)**0.5).astype(dtype=np.int)
distance

[[13 92]
 [70 62]
 [92 82]
 [66 50]
 [40 67]
 [35 86]
 [27 31]
 [20 88]
 [45 82]
 [95 57]]
[[ 121 7921]
 [4624 3481]
 [8100 6241]
 [4096 2209]
 [1444 4096]
 [1089 6889]
 [ 625  784]
 [ 324 7225]
 [1849 6241]
 [8649 2916]]


<ipython-input-29-9ae71d134bfd>:2: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  coordinates=np.random.random_integers(1,100,size=20).reshape(10,2)
<ipython-input-29-9ae71d134bfd>:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  distance=(np.sum(((coordinates-point)**2),axis=1)**0.5).astype(dtype=np.int)


array([ 89,  90, 119,  79,  74,  89,  37,  86,  89, 107])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
a=np.arange(1,(6*7*8)+1).reshape(6,7,8)
a
np.where(a==100)

# 1,5,3

#0 [of first dim  ] - 7*8 = 56
#1[of first dim]
#  0,1,2,3,4 [of 2nd dim ] - 8*5= 40
#            0,1,2 [of 3rd dim]- 3
#                  3rd of 3rd dim will be 100th element [56+40+3 =99]

(array([1]), array([5]), array([3]))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
a=np.array([int(i) for i in input().split()][::-1],dtype=np.float32)
a

1 2 4 -5 0


array([ 0., -5.,  4.,  2.,  1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
def count(a):
  return np.prod(a.shape)
count(a)

30

In [ ]:
a=np.random.random(size=30).reshape(5,6)

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

def softmax(array):
  exp=np.exp(array)
  exp=exp/np.sum(exp)
  return exp

In [ ]:
a=np.array([86.03331084,37.7285648,48.64908087,87.16563062,38.40852563,37.20006318])

In [ ]:
softmax(a)

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



In [3]:
def stack(*arrays):
  a=np.vstack(arrays)
  return a


In [4]:
a=[[0,1,2,3,4],
 [5,6,7,8,9]]

b=[[1,1,1,1,1],
[1,1,1,1,1]]

c=[[0.10117373,0.1677244,0.73764059,0.83166097,0.48985695]
,[0.44581567,0.13502419,0.55692335,0.16479622,0.61193593]]

stack(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [7]:
#Code here
def between_dates(start,end):
  return np.arange(start,end,dtype='datetime64')

between_dates(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [18]:
#code here
def matrix_mean_row(matrix):
  print(np.mean(matrix,axis=1,keepdims=True))
  matrix=matrix-np.mean(matrix,axis=1,keepdims=True
                        )
  return matrix
a=np.random.random_integers(1,100,size=6).reshape(3,2)
print(a)
matrix_mean_row(a)

[[20 72]
 [37 67]
 [ 6 72]]
[[46.]
 [52.]
 [39.]]


<ipython-input-18-81b8d406bb6e>:7: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a=np.random.random_integers(1,100,size=6).reshape(3,2)


array([[-26.,  26.],
       [-15.,  15.],
       [-33.,  33.]])

In [ ]:
np.mean()

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

In [27]:
def swap_columns(array):
  col0=array[:,0]
  array[:,0],array[:,1]=array[:,1],col0
  return array
a=np.random.random_integers(1,100,size=6).reshape(3,2)
print(a)
swap_columns(a)

[[43 50]
 [42 22]
 [ 5 88]]


<ipython-input-27-53a3efb567a9>:5: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a=np.random.random_integers(1,100,size=6).reshape(3,2)


array([[50, 50],
       [22, 22],
       [88, 88]])

###`Q-16:` Replace odd elements in arrays with -1.

In [20]:
#Code here
a=np.random.random_integers(1,100,size=6).reshape(3,2)
print(a)
a[a%2!=0]=-11
a

[[35 47]
 [91 13]
 [11 32]]


<ipython-input-20-d23750d4ae23>:2: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a=np.random.random_integers(1,100,size=6).reshape(3,2)


array([[-11, -11],
       [-11, -11],
       [-11,  32]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [25]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.where(a>b,a,b)

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [43]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3415, 3627, 3961, 6665, 5557],
       [3520, 8680, 1518, 4335, 1691],
       [ 643, 5768,  128, 8555, 6593],
       [1434,  256, 8281, 2876, 8264],
       [7907, 3100, 8440, 9526, 5272],
       [5748, 7007, 2082,  565, 2738],
       [6398, 6839, 7468, 1247, 8220],
       [3127, 3854,  698, 9824, 9605]])

In [44]:
#Code here

# arr1[:,::2]=(arr1[:,::2]-np.min(arr1[:,::2],axis=0))

div=np.max(arr1[:,::2],axis=0)-np.min(arr1[:,::2],axis=0)
print(div)
# arr1[:,::2]
print(np.min(arr1[:,::2],axis=0))

arr1[:,::2]=(arr1[:,::2]-np.min(arr1[:,::2],axis=0))/div
arr1

[7264 8312 7914]
[ 643  128 1691]


array([[   0, 3627,    0, 6665,    0],
       [   0, 8680,    0, 4335,    0],
       [   0, 5768,    0, 8555,    0],
       [   0,  256,    0, 2876,    0],
       [   1, 3100,    1, 9526,    0],
       [   0, 7007,    0,  565,    0],
       [   0, 6839,    0, 1247,    0],
       [   0, 3854,    0, 9824,    1]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [47]:
#Code here
def n_largest(array,n):
  return np.sort(array)[::-1][n-1]

a=np.random.random_integers(1,100,25)
print(a)
print(np.sort(a))
n_largest(a,5)

[ 94  90  80  64  74  95   8  94  17  32  97  95  74  73  89  89 100  26
  25  67   3  62  11  33  98]
[  3   8  11  17  25  26  32  33  62  64  67  73  74  74  80  89  89  90
  94  94  95  95  97  98 100]


<ipython-input-47-fd132c477463>:5: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  a=np.random.random_integers(1,100,25)


95

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [5]:
#code here
import numpy as np
a=np.array([1,2,3])
# np.tile(a,a.size)
# np.repeat(a,a.size)
np.hstack((np.repeat(a,a.size),np.tile(a,a.size)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])